# ui/shared/components/disclaimer_box.py
"""
DISCLAIMER BOX – LEGAL SAFEGUARD UI COMPONENT
=============================================

🚫 GOVERNANCE LOCK – STRICT COMPLIANCE
- Tuân thủ tuyệt đối:
  - MASTER_SPEC.md
  - IMPLEMENTATION STATUS – PART 1 & PART 2

📌 MỤC ĐÍCH
- Hiển thị disclaimer pháp lý & vận hành trong UI
- Nhắc lại ranh giới trách nhiệm giữa:
    ✔ AI
    ✔ Rule-based system
    ✔ Human appraiser / credit officer

📌 NGUYÊN TẮC BẮT BUỘC
- Disclaimer ≠ Warning kỹ thuật
- Disclaimer ≠ Risk signal
- Disclaimer ≠ Điều kiện sử dụng chung chung

Đây là **lá chắn pháp lý**, không phải UX decoration.
"""

import streamlit as st
from typing import Optional


# =========================
# DEFAULT DISCLAIMER TEXT
# =========================

_DEFAULT_DISCLAIMER = """
This system provides **indicative analytical outputs only**.

- AI models and rules **do not replace licensed appraisers**.
- Outputs are **not final valuation conclusions**.
- No result generated by this system constitutes:
  - a legally binding appraisal,
  - a credit approval,
  - or an investment recommendation.

**Final responsibility and judgment remain with qualified human professionals.**
"""


# =========================
# RENDER FUNCTION
# =========================

def render_disclaimer_box( title: Optional[str] = "Important Disclaimer", content: Optional[str] = None, ) -> None: 
    """ Render disclaimer box trong UI. Parameters ---------- title : str | None Tiêu đề hiển thị (trung lập, không gây sợ hãi). content : str | None Nội dung disclaimer. Nếu None → dùng default system disclaimer. GOVERNANCE NOTES ---------------- - Nội dung mang tính pháp lý - Không được sửa nội dung để “thân thiện” hơn - Không được rút gọn làm mất ý nghĩa """ 
    disclaimer_text = content or _DEFAULT_DISCLAIMER 
    st.markdown( f""" <div style=" border: 1px solid #e0e0e0; border-left: 6px solid #b71c1c; background-color: #fff8f8; padding: 1em; margin: 1em 0; border-radius: 4px; "> <div style="font-weight: 600; margin-bottom: 0.5em;"> ⚠️ {title} </div> <div style="font-size: 0.9em; line-height: 1.5;"> {disclaimer_text} </div> </div> """, unsafe_allow_html=True, )
"""
📌 AUDIT & LEGAL NOTES
---------------------
- Component này:
    ✔ BẮT BUỘC xuất hiện tại các màn hình valuation / report
    ✔ Có thể tái sử dụng ở manager / audit view
    ✔ Ngôn ngữ trung lập, không marketing

- Component này KHÔNG ĐƯỢC:
    ❌ dùng để né trách nhiệm
    ❌ thay thế policy document
    ❌ bị ẩn theo feature flag thông thường

Nguyên tắc pháp lý:
"Disclaimer nhắc lại ranh giới – không chuyển giao trách nhiệm."

AI hỗ trợ.  
Human chịu trách nhiệm.
"""
