# Module: valuation_engine/llm_assistant/assumption_summary.py
# Part of Advanced AVM System

"""
valuation_engine/llm_assistant/assumption_summary.py

ROLE:
    LLM-Assisted Assumption Summary Generator (Clerical Only)

GOVERNANCE CLASSIFICATION:
    NHÓM A – Legal / Audit Boundary

AUTHORITATIVE SPEC:
    MASTER_SPEC.md
    IMPLEMENTATION STATUS – assumption_summary.py

CORE PRINCIPLES (ENFORCED):
    - valuation_dossier.json is Single Source of Truth
    - Read-only inputs
    - No computation
    - No inference
    - No decision-making
    - LLM = descriptive clerk only
"""

from typing import Dict, Any, List

from valuation_engine.llm_assistant.llm_guardrails import (
    enforce_llm_guardrails,
    LLMGuardrailViolation,
)


class AssumptionSummaryError(Exception):
    """Raised when assumption summary generation violates governance rules."""


def generate_assumption_summary(
    *,
    assumptions: List[Dict[str, Any]],
    llm_client,
) -> List[str]:
    """
    Generate human-readable summaries of valuation assumptions
    using LLM assistance.

    GOVERNANCE NOTES:
        - This function summarizes EXISTING assumptions only.
        - It does NOT create, modify, rank, or validate assumptions.
        - It does NOT assess reasonableness or impact.
        - All assumptions are treated as immutable facts.

    Parameters
    ----------
    assumptions : List[dict]
        Pre-existing, governance-approved assumptions extracted
        from valuation_dossier.json.

        Each assumption MUST already exist upstream and MUST NOT be:
            - inferred
            - generated by LLM
            - modified in this layer

    llm_client :
        Pre-approved LLM client instance.
        Must NOT be invoked outside guardrails.

    Returns
    -------
    List[str]
        List of descriptive assumption summaries, one per input assumption.

    Raises
    ------
    AssumptionSummaryError
        If any governance or guardrail violation occurs.
    """

    if not isinstance(assumptions, list):
        raise AssumptionSummaryError("assumptions must be a list")

    summaries: List[str] = []

    for idx, assumption in enumerate(assumptions):
        if not isinstance(assumption, dict):
            raise AssumptionSummaryError(
                f"Assumption at index {idx} must be a dict"
            )

        prompt = _build_assumption_prompt(assumption)

        # Invoke LLM exactly once per assumption
        raw_output = llm_client.generate_text(prompt)

        # Enforce guardrails (FAIL-HARD)
        try:
            safe_output = enforce_llm_guardrails(
                text=raw_output,
                section_name="assumption_summary",
            )
        except LLMGuardrailViolation as exc:
            raise AssumptionSummaryError(
                f"LLM output violated guardrails for assumption index {idx}"
            ) from exc

        summaries.append(safe_output)

    return summaries


def _build_assumption_prompt(assumption: Dict[str, Any]) -> str:
    """
    Build a strictly descriptive prompt for summarizing assumptions.

    HARD CONSTRAINTS:
        - No evaluation of validity
        - No assessment of impact
        - No ranking or prioritization
        - No approval or rejection language
        - No numeric reasoning
    """

    return (
        "You are assisting with drafting a neutral summary of valuation assumptions.\n\n"
        "STRICT RULES:\n"
        "- Describe the assumption as stated.\n"
        "- Do NOT judge whether it is reasonable or appropriate.\n"
        "- Do NOT assess impact on value or risk.\n"
        "- Do NOT recommend acceptance or rejection.\n"
        "- Do NOT introduce new assumptions.\n"
        "- Use clear, professional, neutral language.\n\n"
        "ASSUMPTION (READ-ONLY FACT):\n"
        f"{assumption}\n\n"
        "TASK:\n"
        "Rewrite the assumption above into a concise, human-readable description.\n"
    )
