"""
valuation_engine/llm_assistant/limitation_generator.py

ROLE:
    LLM-Assisted Valuation Limitation Generator (Clerical Only)

GOVERNANCE CLASSIFICATION:
    NHÓM A – Legal / Audit Boundary

AUTHORITATIVE SPEC:
    MASTER_SPEC.md
    IMPLEMENTATION STATUS – limitation_generator.py

CORE PRINCIPLES (ENFORCED):
    - valuation_dossier.json is Single Source of Truth
    - Read-only inputs only
    - No computation, no inference
    - No decision-making
    - LLM = descriptive clerk, not valuer
"""

from typing import List, Dict, Any

from valuation_engine.llm_assistant.llm_guardrails import (
    enforce_llm_guardrails,
    LLMGuardrailViolation,
)


class LimitationGenerationError(Exception):
    """Raised when limitation generation violates governance rules."""


def generate_valuation_limitations(
    *,
    limitation_facts: List[Dict[str, Any]],
    llm_client,
) -> List[str]:
    """
    Generate human-readable valuation limitations using LLM assistance.

    GOVERNANCE NOTES:
        - This function ONLY rewrites EXISTING limitation facts.
        - It does NOT create new limitations.
        - It does NOT assess severity, impact, or adequacy.
        - It does NOT prioritize or rank limitations.
        - All inputs are immutable facts from upstream artifacts.

    Parameters
    ----------
    limitation_facts : List[dict]
        Pre-existing limitation facts extracted from valuation_dossier.json
        or governance-approved registries.

        Each item MUST already exist and MUST NOT be:
            - inferred
            - generated by LLM
            - modified by this component

    llm_client :
        Pre-approved LLM client instance.
        Must only be invoked through this controlled interface.

    Returns
    -------
    List[str]
        List of descriptive limitation statements, one per input fact.

    Raises
    ------
    LimitationGenerationError
        If any governance or guardrail violation occurs.
    """

    if not isinstance(limitation_facts, list):
        raise LimitationGenerationError("limitation_facts must be a list")

    limitations: List[str] = []

    for idx, fact in enumerate(limitation_facts):
        if not isinstance(fact, dict):
            raise LimitationGenerationError(
                f"Limitation fact at index {idx} must be a dict"
            )

        prompt = _build_limitation_prompt(fact)

        # Invoke LLM exactly once per limitation
        raw_output = llm_client.generate_text(prompt)

        # Enforce guardrails (FAIL-HARD)
        try:
            safe_output = enforce_llm_guardrails(
                text=raw_output,
                section_name="valuation_limitations",
            )
        except LLMGuardrailViolation as exc:
            raise LimitationGenerationError(
                f"LLM output violated guardrails for limitation index {idx}"
            ) from exc

        limitations.append(safe_output)

    return limitations


def _build_limitation_prompt(limitation_fact: Dict[str, Any]) -> str:
    """
    Build a strictly descriptive prompt for valuation limitations.

    HARD CONSTRAINTS:
        - No legal advice
        - No interpretation of liability
        - No assessment of sufficiency
        - No suggestion of mitigation
        - No numeric or probabilistic reasoning
    """

    return (
        "You are assisting with drafting valuation report limitations.\n\n"
        "STRICT RULES:\n"
        "- Restate the limitation as a factual constraint.\n"
        "- Do NOT assess legal impact or responsibility.\n"
        "- Do NOT evaluate severity or materiality.\n"
        "- Do NOT suggest actions, mitigations, or decisions.\n"
        "- Do NOT introduce new limitations.\n"
        "- Use neutral, formal, professional language.\n\n"
        "LIMITATION FACT (READ-ONLY):\n"
        f"{limitation_fact}\n\n"
        "TASK:\n"
        "Rewrite the limitation above into a clear, human-readable limitation statement.\n"
    )
