# ui/appraiser/components/warning_panel.py
"""
WARNING PANEL – APPRAISER VIEW
==============================

🚫 GOVERNANCE LOCK – STRICT COMPLIANCE
Tuân thủ tuyệt đối:
- MASTER_SPEC.md
- IMPLEMENTATION STATUS – PART 1 & PART 2

📌 MỤC ĐÍCH
- Hiển thị các cảnh báo (warnings / flags) do hệ thống sinh ra
- Hỗ trợ thẩm định viên:
    ✔ nhận biết rủi ro
    ✔ chú ý các điểm bất thường
    ✔ phục vụ giải trình & audit

📌 NGUYÊN TẮC BẤT BIẾN
- READ-ONLY tuyệt đối
- KHÔNG:
    ❌ suy diễn mức độ nghiêm trọng mới
    ❌ gộp / xoá cảnh báo
    ❌ quyết định phê duyệt hay từ chối

📌 Warning = tín hiệu kiểm soát, KHÔNG phải kết luận
"""

import streamlit as st
from typing import List, Dict, Any

from ui.shared.auth.role_guard import require_role
from ui.shared.state.role_state import Role
from ui.shared.components.disclaimer_box import render_disclaimer
from ui.shared.utils.safe_render import safe_markdown


# =========================
# MAIN RENDER
# =========================

def render_warning_panel(
    warnings: List[Dict[str, Any]],
) -> None:
    """
    Render panel cảnh báo.

    Parameters
    ----------
    warnings : List[Dict[str, Any]]
        Ví dụ:
        [
            {
                "code": "LOW_DATA_COVERAGE",
                "level": "HIGH",
                "message": "Comparable data coverage is below minimum threshold.",
                "source": "Data Quality Engine"
            },
            {
                "code": "MODEL_DISPERSION",
                "level": "MEDIUM",
                "message": "High dispersion detected across core models.",
                "source": "Ensemble Monitor"
            }
        ]

    GOVERNANCE
    ----------
    - Warnings phải đến từ valuation_dossier
    - UI không được tạo hay chỉnh sửa cảnh báo
    """

    # =========================
    # ROLE GUARD
    # =========================
    if not require_role(
        [Role.APPRAISER, Role.MANAGER, Role.AUDITOR],
        message="Warning panel is restricted to appraisal roles.",
    ):
        return

    st.subheader("⚠️ System Warnings & Flags")

    render_disclaimer(
        title="Governance Notice",
        message=(
            "Warnings shown below are generated by governed system checks. "
            "They indicate potential risks or limitations and MUST be reviewed "
            "by a qualified human appraiser."
        ),
        level="warning",
    )

    if not warnings:
        st.success("No system warnings detected.")
        return

    # =========================
    # RENDER WARNINGS
    # =========================
    for warning in warnings:
        level = warning.get("level", "INFO").upper()
        code = warning.get("code", "UNKNOWN")
        message = warning.get("message", "")
        source = warning.get("source", "System")

        header = f"[{level}] {code}"
        body = f"{message}\n\n_Source: {source}_"

        if level == "HIGH":
            st.error(f"❗ {header}\n\n{body}")
        elif level == "MEDIUM":
            st.warning(f"⚠️ {header}\n\n{body}")
        else:
            st.info(f"ℹ️ {header}\n\n{body}")

    # =========================
    # AUDIT FOOTNOTE
    # =========================
    safe_markdown(
        """
**Audit Notes**
- Warnings are *signals*, not decisions.
- Presence of warnings does NOT invalidate valuation automatically.
- All warnings must be acknowledged during human review.

_No warning is ignored. No warning decides alone._
        """
    )


"""
📌 AUDIT & LEGAL NOTES
---------------------
- Warning Panel:
    ✔ Bắt buộc cho kiểm soát rủi ro
    ✔ Phục vụ credit review & audit trail
    ✔ Minh bạch hoá giới hạn hệ thống

Nguyên tắc bất biến:
"Cảnh báo để con người quyết – không để AI quyết."

AI phát hiện rủi ro.  
Con người chịu trách nhiệm xử lý.
"""
